### ISSUE TITLE
Question: Integration with Spring?

### ISSUE THREAD

**Issue by tobiastimm** [liquibase/liquibase-groovy-dsl#16]
Can't get this working with spring-shell.

In my applicationContext.xml i declare liquibase

```
<bean id="liquibase" class="liquibase.integration.spring.SpringLiquibase" depends-on="postgresService">
        <property name="dataSource" ref="psqlDataSource"/>
        <property name="changeLog" value="com.example.db.DbChangelog_master"/>
        <property name="defaultSchema" value="${postgres.schema}"/>
    </bean>
```

The jar is also included in my classpath, but everytime i get the exception

```
Caused by: liquibase.exception.UnknownChangelogFormatException: Cannot find parser that supports com.example.db.DbChangelog_master
    at liquibase.parser.ChangeLogParserFactory.getParser(ChangeLogParserFactory.java:70)
    at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:226)
    at liquibase.Liquibase.update(Liquibase.java:202)
    at liquibase.Liquibase.update(Liquibase.java:192)
    at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:434)
    at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:391)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
    ... 13 more
```

**Comment by tobiastimm** [comment]
Was an error caused by myself
