### ISSUE TITLE
Support Serializing (generateChangeLog/Diff)

### ISSUE THREAD

**Issue by dgeissl** [liquibase/liquibase-groovy-dsl#25]
Trying to output a existing database or a diff to groovy does not work at the moment. I guess that feature has not been implemented yet?
```
$ ./liquibase --changeLogFile=output.groovy --logLevel=warning generateChangeLog
Unexpected error running Liquibase: java.lang.RuntimeException: No serializers associated with the filename or extension 'output.groovy'

SEVERE 27.01.17 10:28: liquibase: java.lang.RuntimeException: No serializers associated with the filename or extension 'output.groovy'
liquibase.exception.LiquibaseException: liquibase.command.CommandExecutionException: java.lang.RuntimeException: No serializers associated with the filename or extension 'output.groovy'
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:265)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1011)
        at liquibase.integration.commandline.Main.run(Main.java:188)
        at liquibase.integration.commandline.Main.main(Main.java:103)
Caused by: liquibase.command.CommandExecutionException: java.lang.RuntimeException: No serializers associated with the filename or extension 'output.groovy'
        at liquibase.command.AbstractCommand.execute(AbstractCommand.java:13)
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:263)
        ... 3 more
Caused by: java.lang.RuntimeException: No serializers associated with the filename or extension 'output.groovy'
        at liquibase.serializer.ChangeLogSerializerFactory.getSerializer(ChangeLogSerializerFactory.java:55)
        at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:74)
        at liquibase.command.GenerateChangeLogCommand.run(GenerateChangeLogCommand.java:54)
        at liquibase.command.AbstractCommand.execute(AbstractCommand.java:8)
        ... 4 more
```

**Comment by dgeissl** [comment]
Sorry for the inconvinience this ticket can be closed as it was just a classpath issue.
I missed to copy the groovy and groovy-sql jar s in the lib folder, this way the plugin was not actualy active.

**Comment by rsinkwitz** [comment]
I'm getting the same running "liquibase  --changeLogFile=generated.groovy generateChangeLog"
It is fine for XML/JSON/YAML. I've downloaded liquibase, placed liquibase-groovy-dsl-2.0.3.jar in the lib directory of liquibase. What else exactly do I need to do?
Please help, regards, Rainer

**Comment by stevesaliman** [comment]
Sorry for the delay in responding, it's been a busy week.

The Liquibase Groovy DSL needs Groovy itself on the classpath before it can handle Groovy changesets.  Try copying the groovy-x.y.z.jar file from a Groovy distribution into the lib directory of liquibase.  Does that solve the problem?
