### ISSUE TITLE
'dropTable' is not a valid element of a ChangeSet

### ISSUE THREAD

**Issue by oleksii-kondratiuk** [liquibase/liquibase-groovy-dsl#42]
Hello!

I created very simple changeset:
``` groovy
databaseChangeLog {
    changeSet(id: '1', author: 'oleksii') {
        rollback {
            dropTable(schemaName = "public", tableName = "website_city")
        }
    }
}
```

I run rollback using gradle plugin:
`gradle rollbackCount -PliquibaseCommandValue=1`

But I am getting next exception:
``` Java
Unexpected error running Liquibase: ChangeSet '1': 'dropTable' is not a valid element of a ChangeSet
liquibase.exception.ChangeLogParseException: ChangeSet '1': 'dropTable' is not a valid element of a ChangeSet
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
```

Here are Gradle dependencies with versions that I am using in the project:
``` Groovy
liquibaseRuntime 'org.liquibase:liquibase-gradle-plugin:2.0.1'
liquibaseRuntime 'org.liquibase:liquibase-core:3.6.1'
liquibaseRuntime 'org.liquibase:liquibase-groovy-dsl:2.0.1'
liquibaseRuntime 'org.codehaus.groovy:groovy:2.5.7'
```

Not sure whether I`m doing something wrong or it is a bug in the plugin itself. Can you help me with this?

**Comment by stevesaliman** [comment]
I think the problem is with the way you're declaring the `dropTable` change.  It should be `dropTable(schemaName: "public", tableName: "website_city")` with colons instead of equals.

The error message you get about dropTable being invalid is misleading - dropTable is valid - but the Groovy parser is getting confused by the equals signs.
