### ISSUE TITLE
NPE on customChange

### ISSUE THREAD

**Issue by vporoxnenko** [liquibase/liquibase-groovy-dsl#5]
I got an issue with customChange dsl

my changelog is pretty trivial

databaseChangeLog() {

  changeSet(author: 'pupseg', id: 'test-1') {
    customChange(class: 'my.VelocityTaskChange') {
        param(name: 'param1', value: 'param1value')
    }
  }

public class VelocityTaskChange implements CustomTaskChange
do nothing right now

error on execution caused because customChange field is not initialized on liquibase validation stage and configureCustomChange() method called for null customChange object

liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.CustomChangeException: java.lang.NullPointerException
        at liquibase.change.custom.CustomChangeWrapper.validate(CustomChangeWrapper.java:144)
        at liquibase.changelog.visitor.ValidatingVisitor.visit(ValidatingVisitor.java:117)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:73)
        at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:199)
        at liquibase.Liquibase.update(Liquibase.java:206)
        at liquibase.Liquibase.update(Liquibase.java:190)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1096)
        at liquibase.integration.commandline.Main.run(Main.java:180)
        at liquibase.integration.commandline.Main.main(Main.java:99)
Caused by: liquibase.exception.CustomChangeException: java.lang.NullPointerException
        at liquibase.change.custom.CustomChangeWrapper.configureCustomChange(CustomChangeWrapper.java:253)
        at liquibase.change.custom.CustomChangeWrapper.validate(CustomChangeWrapper.java:142)
        ... 8 more
Caused by: java.lang.NullPointerException
        at liquibase.util.ObjectUtil.getMethods(ObjectUtil.java:136)
        at liquibase.util.ObjectUtil.getWriteMethod(ObjectUtil.java:125)
        at liquibase.util.ObjectUtil.setProperty(ObjectUtil.java:50)
        at liquibase.change.custom.CustomChangeWrapper.configureCustomChange(CustomChangeWrapper.java:248)
        ... 9 more
liquibase.exception.ValidationFailedException: Validation Failed:
     1 changes have validation errors
          liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.CustomChangeException: java.lang.NullPointerException

```
    at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:206)
    at liquibase.Liquibase.update(Liquibase.java:206)
    at liquibase.Liquibase.update(Liquibase.java:190)
    at liquibase.integration.commandline.Main.doMigration(Main.java:1096)
    at liquibase.integration.commandline.Main.run(Main.java:180)
    at liquibase.integration.commandline.Main.main(Main.java:99)
```

**Comment by vporoxnenko** [comment]
by the way groov-dsl is more compact and extensible than xml, thank you for yours job )

**Comment by vporoxnenko** [comment]
just tested with xml
DatabaseChangeLog.load(...) method called before any kind of validation, so CustomChangeWrapper.customChange field will be implemented on validation phase

**Comment by stevesaliman** [comment]
Version 1.2.1, with Pull Request #6 has been published.
